<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>JS Errors</title>
  </head>
  <body>
    <h2>JavaScript Errors</h2>
    <h3>Try...Catch...Finally and Throw</h3>
    <p>The <b> try </b> statement defines a code block to run (to try).</p>
    <p>The <b> catch </b> statement defines a code block to handle any error.</p>
    <p>The <b> finally </b> statement defines a code block to run regardless of the result.</p>
    <p>The <b> throw </b> statement defines a custom error.</p>
    <p>How to use <b>catch</b> to display an error.</p>
    <p>Let's make a mistake of misspelled "alert" as "adddlert" to deliberately produce an error:</p>

    <h3>JavaScript try and catch</h3>
    <p>The try statement allows you to define a block of code to be tested for errors while it is being executed.</p>
    <p>The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.</p>
    <p>The JavaScript statements try and catch come in pairs:</p>
    <pre>
        try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}
    </pre>
    <script>
      try {
        adddlert("Welcome guest!");
      } catch (err) {
        document.write(err.message); // err is an error object automatically created by JavaScript. The err object contains useful information about the error.
      }
    </script>

    <p>JavaScript catches adddlert as an error, and executes the catch code to handle it.</p>

    <h3>JavaScript Throws Errors</h3>
    <p>When an error occurs, JavaScript will normally stop and generate an error message.</p>
    <p>The technical term for this is: JavaScript will <b> throw an exception (throw an error) </b>.</p>
    <p>
      JavaScript will actually create an <b> Error object </b> with two properties: <b> name </b> and <b>message</b>.
    </p>

    <p>ðŸ”¹ Example: Logging the Error Object</p>

    <script>
      try {
        adddlert("Hello!");
      } catch (err) {
        console.log(err); // Logs the full error object
        console.log(err.name); //Type of error... ReferenceError
        console.log(err.message);
      } //Error description.... adddlert is not defined
    </script>

    <h3>The throw Statement</h3>
    <p>
      The throw statement allows you to create a custom error. Technically you can throw an exception (throw an error).
    </p>
    <p>The exception can be a JavaScript String, a Number, a Boolean or an Object:</p>

    <pre>
        throw "Too big";    // throw a text
         throw 500;          // throw a number
    </pre>
    <p>
      If you use throw together with try and catch, you can control program flow and generate custom error messages.
    </p>

    <h3>Input Validation Example</h3>
    <pre>
        This example examines input. If the value is wrong, an exception (err) is thrown.
        The exception (err) is caught by the catch statement and a custom error message is displayed:
    </pre>
    <h2>JavaScript try catch</h2>

    <p>Please input a number between 5 and 10:</p>

    <input id="demo" type="text" />
    <button type="button" onclick="myFunction1()">Test Input</button>
    <p id="p01"></p>

    <script>
      function myFunction1() {
        const message = document.getElementById("p01");
        message.innerHTML = "";
        let x = document.getElementById("demo").value;
        try {
          if (x.trim() == "") throw "empty";
          if (isNaN(x)) throw "not a number";
          x = Number(x);
          if (x < 5) throw "too low";
          if (x > 10) throw "too high";
        } catch (err) {
          message.innerHTML = "Input is " + err;
        }
      }
    </script>
    <h3>finally Statement</h3>
    <p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>
    <pre>
        Syntax

        try {
        Block of code to try
        }
        catch(err) {
        Block of code to handle errors
        }
        finally {
        Block of code to be executed regardless of the try / catch result
        }
    </pre>

    <p>Please input a number between 5 and 120:</p>

    <input id="demoF" type="text" />
    <button type="button" onclick="myFunction2()">Test Input</button>
    <p id="p01F"></p>

    <script>
      function myFunction2() {
        const message = document.getElementById("p01F");
        message.innerHTML = "";
        let x = document.getElementById("demoF").value;
        try {
          if (x.trim() == "") throw "is empty";
          if (isNaN(x)) throw "is not a number";
          x = Number(x);
          if (x > 10) throw "is too high";
          if (x < 5) throw "is too low";
        } catch (err) {
          message.innerHTML = "Input " + err;
        } finally {
          document.getElementById("demoF").value = "";
        }
      }
    </script>
    <h3>The Error Object</h3>
    <p>JavaScript has a built in error object that provides error information when an error occurs.</p>
    <p>The error object provides two useful properties: name and message.</p>

    <pre>
    Error Object Properties
Property	          Description
name	       Sets or returns an error name
message	       Sets or returns an error message (a string)
   </pre
    >

    <pre>
    Error Name Values
Six different values can be returned by the error name property:

Error Name	         Description
EvalError	    An error has occurred in the eval() function
RangeError	    A number "out of range" has occurred
ReferenceError 	An illegal reference has occurred  //A ReferenceError is thrown if you use (reference) a variable that has not been declared:
SyntaxError 	A syntax error has occurred
TypeError	    A type error has occurred //A TypeError is thrown if an operand or argument is incompatible with the type expected by an operator or function. e.g , number.toUppperCase()
URIError	    An error in encodeURI() has occurred //A URIError is thrown if you use illegal characters in a URI function: //decodeURI("%%%");
   </pre
    >
    <h2>Use Strict</h2>
    <p>
      Strict mode makes it easier to write "secure" JavaScript. Strict mode changes previously accepted "bad syntax"
      into real errors.
    </p>
    <p>"use strict"; Defines that JavaScript code should be executed in "strict mode".</p>
    <pre>
       "use strict";
        x = 3.14; // This will cause an error because x is not declared</pre
    >
    <pre>
        Declared inside a function, it has local scope (only the code inside the function is in strict mode):
        x = 3.14;       // This will not cause an error.
        myFunction();

            function myFunction() {
            "use strict";
            y = 3.14;   // This will cause an error
            }
    </pre>
    <pre>
        "use strict";
        myFunction();

        function myFunction() {
        y = 3.14;   // This will also cause an error because y is not declared
        }
    </pre>
    <pre>
        The words (eval , arguments ) cannot be used as a variable in strict mode
          "use strict";
          let eval = 3.14;         // This will cause an error
    </pre>

    <script>
      const thisObj = {
        name: "Khalid Khan",
        age: 35,
      };
    </script>
    <pre>
        The this keyword in functions behaves differently in strict mode.
        The this keyword refers to the object that calls the function.
        If the object is not specified, functions in strict mode will return undefined and functions in normal mode will return the global object (window):
    </pre>
    <script>
      "use strict"; // Remove this line to see another behaviour
      function myFunction3() {
        alert(this); // will alert "undefined"
      }
      document.write(myFunction3());
    </script>
  </body>
</html>
